const cities = [
    "Abbottabad",
    "Adezai",
    "Ahmadpur East",
    "Ahmed Nager Chatha",
    "Alipur",
    "Alpuri",
    "Arifwala",
    "Attock",
    "Ayubia",
    "Badin",
    "Bahawalnagar",
    "Bahawalpur",
    "Banda Daud Shah",
    "Bannu",
    "Batkhela",
    "Battagram",
    "Bhakkar",
    "Bhalwal",
    "Birote",
    "Burewala",
    "Chakdara",
    "Chakwal",
    "Chaman",
    "Charsadda",
    "Chichawatni",
    "Chillianwala",
    "Chiniot",
    "Chishtian",
    "Chitral",
    "Dadu",
    "Daggar",
    "Dargai",
    "Darya Khan",
    "Daska",
    "Dera Allah Yar",
    "Dera Ghazi Khan",
    "Dera Ismail Khan",
    "Dera Murad Jamali",
    "Dhaular",
    "Digri",
    "Dina",
    "Dinga",
    "Dipalpur",
    "Diplo",
    "Dir",
    "Dokri",
    "Drosh",
    "Faisalabad",
    "Fateh Jang",
    "Ghakhar Mandi",
    "Ghotki",
    "Gilgit",
    "Gojra",
    "Gujar Khan",
    "Gujranwala",
    "Gujrat",
    "Gwadar",
    "Haala",
    "Hafizabad",
    "Hangu",
    "Haripur",
    "Haroonabad",
    "Hasilpur",
    "Haveli Lakha",
    "Hub",
    "Hyderabad",
    "Islamabad",
    "Islamkot",
    "Jacobabad",
    "Jalalpur Jattan",
    "Jampur",
    "Jamshoro",
    "Jaranwala",
    "Jauharabad",
    "Jhang",
    "Jhelum",
    "Jungshahi",
    "Kalabagh",
    "Kalat",
    "Kamalia",
    "Kamoke",
    "Kandiaro",
    "Karachi",
    "Karak",
    "Karor Lal Esan",
    "Kashmore",
    "Kasur",
    "Keti Bandar",
    "Khairpur",
    "Khanewal",
    "Khanpur",
    "Kharan",
    "Kharian",
    "Khushab",
    "Khuzdar",
    "Kohat",
    "Kot Adu",
    "Kotri",
    "Lahore",
    "Lakki Marwat",
    "Lalamusa",
    "Larkana",
    "Latamber",
    "Layyah",
    "Liaquat Pur",
    "Lodhran",
    "Loralai",
    "Madyan",
    "Mailsi",
    "Mamoori",
    "Mandi Bahauddin",
    "Mansehra",
    "Mardan",
    "Mastuj",
    "Mastung",
    "Matiari",
    "Mehar",
    "Mehrabpur",
    "Mian Channu",
    "Mianwali",
    "Mingora",
    "Mirpur Khas",
    "Mithani",
    "Mithi",
    "Moro",
    "Multan",
    "Muridke",
    "Murree",
    "Muzaffarabad",
    "Muzaffargarh",
    "Nagarparkar",
    "Narowal",
    "Naudero",
    "Naushahro Feroze",
    "Naushara",
    "Nawabshah",
    "Nazimabad",
    "Nowshera",
    "Nushki",
    "Okara",
    "Paharpur",
    "Pakpattan",
    "Pasni",
    "Pattoki",
    "Peshawar",
    "Pir Mahal",
    "Qila Didar Singh",
    "Quetta",
    "Rabwah",
    "Rahim Yar Khan",
    "Raiwind",
    "Rajanpur",
    "Rajo Khanani",
    "Ranipur",
    "Ratodero",
    "Rawalpindi",
    "Renala Khurd",
    "Rohri",
    "Sadiqabad",
    "Safdarabad",
    "Sahiwal",
    "Saidu Sharif",
    "Sakrand",
    "Sanghar",
    "Sangla Hill",
    "Sarai Alamgir",
    "Sargodha",
    "Shahbandar",
    "Shahdadkot",
    "Shahdadpur",
    "Shahpur Chakar",
    "Shakargarh",
    "Sheikhupura",
    "Shikarpaur",
    "Sialkot",
    "Sibi",
    "Sohawa",
    "Soianwala",
    "Sukkur",
    "Swabi",
    "Swat",
    "Talagang",
    "Tando Adam Khan",
    "Tando Allahyar",
    "Tangi",
    "Tank",
    "Taxila",
    "Thall",
    "Thatta",
    "Timergara",
    "Toba Tek Singh",
    "Tordher",
    "Turbat",
    "Umerkot",
    "Usta Mohammad",
    "Vehari",
    "Wah Cantonment",
    "Warah",
    "Wazirabad",
    "Zhob"
]

export { cities };